### ISSUE TITLE
Reference sprites by locally

### ISSUE THREAD

**Issue by SchillingSebastian** [openmaptiles/toner-gl-style#11]
I also opened the same issue at the positron style https://github.com/openmaptiles/positron-gl-style/issues/19
The current sprites are referenced by url. Here is a to the [reference line](  "sprite": "https://openmaptiles.github.io/maptiler-toner-gl-style/sprite",)
If a newbie downloads the json, puts it into its tileserver-gl and there is no internet connection he receives 500er errors. 
Please provide the sprites as a local path OR alter the readme with a section regarding foreign urls.

See https://tileserver.readthedocs.io/en/latest/config.html#sprites for more information on how sprites are accessed by tileserver-gl.

I also opened an issue on tileserver-gl to provide better error logs for inaccessible network files https://github.com/maptiler/tileserver-gl/issues/557

**Comment by TomPohys** [comment]
Hi, for [new release v1.0](https://github.com/openmaptiles/maptiler-toner-gl-style/releases/tag/v1.0) there is also `v1.0.zip` with content of `gh-pages` branch, where is also included `style-local.json` for use on your server.
